// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var pattern;

  pattern = require("./pattern");

  module.exports = function(yiai) {
    return yiai.initConfig({
      dest: "./dest",
      origin: "http://localhost:8098",
      filelist: "filelist.txt",
      patterns: pattern
    });
  };

}).call(this);
